version: "3.9"

volumes:
  postgres-data:
  minio_data:
  redis_data:

networks:
  net:

services:
  translator-postgres:
    container_name: translator-postgres
    image: postgres:15
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5452:5432"

  minio:
    container_name: translator-minio
    image: minio/minio:latest
    env_file: .env
    volumes:
      - minio_data:/data
    restart: unless-stopped
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web UI
    command: server /data --console-address ":9001"

  redis:
    container_name: translator-redis
    image: redis:6.2-alpine
    env_file: .env
    volumes:
      - redis_data:/data
    restart: on-failure
    ports:
      - "6379:6379"
    networks:
      - net




