"""Added line

Revision ID: 025336e438e9
Revises: d646860f82a2
Create Date: 2024-09-30 17:22:55.955410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '025336e438e9'
down_revision: Union[str, None] = 'd646860f82a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line',
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('file_sid', sa.Uuid(), nullable=False),
    sa.Column('meaning', sa.String(), nullable=False),
    sa.Column('translation', sa.String(), nullable=False),
    sa.Column('translated', sa.Boolean(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['file_sid'], ['projects.file.sid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sid', 'file_sid'),
    sa.UniqueConstraint('sid'),
    schema='projects'
    )
    op.create_index(op.f('ix_projects_line_meaning'), 'line', ['meaning'], unique=True, schema='projects')
    op.create_index(op.f('ix_projects_line_translation'), 'line', ['translation'], unique=True, schema='projects')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_line_translation'), table_name='line', schema='projects')
    op.drop_index(op.f('ix_projects_line_meaning'), table_name='line', schema='projects')
    op.drop_table('line', schema='projects')
    # ### end Alembic commands ###
