"""updated_field_line

Revision ID: 178501f11201
Revises: 4594d61584e9
Create Date: 2025-03-05 23:17:07.299883

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "178501f11201"
down_revision: Union[str, None] = "4594d61584e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "line",
        sa.Column("group", sa.VARCHAR(length=225), nullable=False),
        schema="projects",
    )
    op.add_column(
        "line",
        sa.Column("filename", sa.VARCHAR(length=1024), nullable=True),
        schema="projects",
    )
    op.add_column(
        "line", sa.Column("line", sa.Integer(), nullable=True), schema="projects"
    )
    op.create_index(
        op.f("ix_projects_line_filename"), "line", ["filename"], schema="projects"
    )
    op.create_index(
        op.f("ix_projects_line_group"),
        "line",
        ["group"],
        schema="projects",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_line_group"), table_name="line", schema="projects")
    op.drop_index(
        op.f("ix_projects_line_filename"), table_name="line", schema="projects"
    )
    op.drop_column("line", "line", schema="projects")
    op.drop_column("line", "filename", schema="projects")
    op.drop_column("line", "group", schema="projects")
    # ### end Alembic commands ###
