"""save_file_db

Revision ID: 3f0d656b2dfb
Revises: ddc71fccf9d3
Create Date: 2025-03-11 21:47:02.877163

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f0d656b2dfb"
down_revision: Union[str, None] = "ddc71fccf9d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file",
        sa.Column("source_bytes", sa.LargeBinary(), nullable=True),
        schema="projects",
    )
    op.drop_column("file", "path", schema="projects")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file",
        sa.Column("path", sa.VARCHAR(), autoincrement=False, nullable=True),
        schema="projects",
    )
    op.drop_column("file", "source_bytes", schema="projects")
    # ### end Alembic commands ###
