"""unique_project_name

Revision ID: 4594d61584e9
Revises: 025336e438e9
Create Date: 2025-03-04 22:03:56.599381

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4594d61584e9"
down_revision: Union[str, None] = "025336e438e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_projects_project_name", table_name="project", schema="projects")
    op.create_index(
        op.f("ix_projects_project_name"),
        "project",
        ["name"],
        unique=True,
        schema="projects",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_projects_project_name"), table_name="project", schema="projects"
    )
    op.create_index(
        "ix_projects_project_name", "project", ["name"], unique=False, schema="projects"
    )
    # ### end Alembic commands ###
