"""add language in file

Revision ID: 5aedb8846e69
Revises: b78756c51418
Create Date: 2025-05-19 23:32:41.069746

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5aedb8846e69"
down_revision: Union[str, None] = "b78756c51418"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file",
        sa.Column("source_language", sa.VARCHAR(), nullable=True),
        schema="projects",
    )
    op.add_column(
        "file",
        sa.Column("translate_language", sa.VARCHAR(), nullable=True),
        schema="projects",
    )
    op.create_index(
        op.f("ix_projects_file_source_language"),
        "file",
        ["source_language"],
        unique=False,
        schema="projects",
    )
    op.create_index(
        op.f("ix_projects_file_translate_language"),
        "file",
        ["translate_language"],
        unique=False,
        schema="projects",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_projects_file_translate_language"),
        table_name="file",
        schema="projects",
    )
    op.drop_index(
        op.f("ix_projects_file_source_language"), table_name="file", schema="projects"
    )
    op.drop_column("file", "translate_language", schema="projects")
    op.drop_column("file", "source_language", schema="projects")
    # ### end Alembic commands ###
