"""img_in_projects

Revision ID: 713170eec377
Revises: 360dc99e2c29
Create Date: 2025-06-03 00:23:48.214064

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "713170eec377"
down_revision: Union[str, None] = "360dc99e2c29"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "project", sa.Column("img", sa.String(), nullable=True), schema="projects"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "img", schema="projects")
    # ### end Alembic commands ###
