"""Added project

Revision ID: 843cdc003ce7
Revises: 81e90cd2877d
Create Date: 2024-09-26 16:43:57.261427

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '843cdc003ce7'
down_revision: Union[str, None] = '81e90cd2877d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
                    sa.Column('sid', sa.Uuid(), nullable=False),
                    sa.Column('user_sid', sa.Uuid(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=225), nullable=False),
                    sa.Column('description', sa.String(), nullable=False),
                    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
                    sa.ForeignKeyConstraint(['user_sid'], ['users.user.sid'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('sid', 'user_sid'),
                    sa.UniqueConstraint('sid'),
                    schema='projects'
                    )
    op.create_index(op.f('ix_projects_project_name'), 'project', ['name'], unique=False, schema='projects')
    op.create_unique_constraint(None, 'role', ['sid'], schema='security')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("role_sid_key", 'role', schema='security', type_='unique')
    op.drop_index(op.f('ix_projects_project_name'), table_name='project', schema='projects')
    op.drop_table('project', schema='projects')
    # ### end Alembic commands ###
