"""Added file

Revision ID: d646860f82a2
Revises: 843cdc003ce7
Create Date: 2024-09-30 17:13:21.629887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd646860f82a2'
down_revision: Union[str, None] = '843cdc003ce7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file',
    sa.Column('sid', sa.Uuid(), nullable=False),
    sa.Column('project_sid', sa.Uuid(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_sid'], ['projects.project.sid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sid', 'project_sid'),
    sa.UniqueConstraint('sid'),
    schema='projects'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('file', schema='projects')
    # ### end Alembic commands ###
