"""updated_field_file

Revision ID: ddc71fccf9d3
Revises: 178501f11201
Create Date: 2025-03-05 23:28:45.366090

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ddc71fccf9d3"
down_revision: Union[str, None] = "178501f11201"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file",
        sa.Column("name", sa.VARCHAR(length=225), nullable=False),
        schema="projects",
    )
    op.alter_column(
        "file",
        "path",
        nullable=True,
        schema="projects",
    )
    op.create_index(
        op.f("ix_projects_file_name"), "file", ["name"], unique=True, schema="projects"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f("ix_projects_file_name"), table_name="file", schema="projects")
    op.drop_column("file", "name", schema="projects")
    op.alter_column(
        "file",
        "path",
        nullable=False,
        schema="projects",
    )

    # ### end Alembic commands ###
